// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// prunespikes
NumericMatrix prunespikes(NumericMatrix spikes, double minisi);
RcppExport SEXP rephys_prunespikes(SEXP spikesSEXP, SEXP minisiSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type spikes(spikesSEXP);
    Rcpp::traits::input_parameter< double >::type minisi(minisiSEXP);
    __result = Rcpp::wrap(prunespikes(spikes, minisi));
    return __result;
END_RCPP
}
