# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name prunespikes
#'
#' @title prunespikes
#' @description A C++ implementation of a demanding function
#' @param spikes spike matrix to be pruned
#' @param minisi minimum inter stimulus interval in milliseconds
#' @return a matrix containing a pruned spike
#' @export
NULL

prunespikes <- function(spikes, minisi) {
    .Call('rephys_prunespikes', PACKAGE = 'rephys', spikes, minisi)
}

